---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ztna

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - intermediate-server.yaml
  - app-connector.yaml
  - echo-server.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/version: "0.1.0"
    includeSelectors: false
