---
# Cilium L2 Announcement Policy
# Enables L2 (ARP) announcements for LoadBalancer services on the local network
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: ztna-l2-policy
spec:
  # Announce LoadBalancer service IPs
  loadBalancerIPs: true
  # Interface to use for L2 announcements (Pi eth0)
  interfaces:
    - ^eth0$
  # Apply to all Linux nodes
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
# Cilium LoadBalancer IP Pool
# Defines the IP range available for LoadBalancer services
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ztna-ip-pool
spec:
  # IP range for ZTNA LoadBalancer services
  # Using 10.0.150.200-210 to avoid conflict with node IPs (101-108)
  blocks:
    - start: "10.0.150.200"
      stop: "10.0.150.210"
